In [39]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [40]:
df= pd.read_csv('../data/cnc_lathe_dataset.csv')

In [41]:
df

,sample_id,timestamp_s,spindle_speed_rpm,feed_rate_mm_min,depth_of_cut_mm,cutting_speed_m_min,material_hardness_HRC,spindle_motor_current_A,spindle_torque_Nm,spindle_temp_C,...,ambient_temp_C,vibration_x_g,vibration_y_g,vibration_z_g,surface_roughness_Ra,dimensional_error_mm,tool_wear_mm,cycle_time_s,tool_condition,fault_label
0,1,12.5,1319,183.8,1.61,0.33,47.9,13.66,18.83,60.3,...,29.7,0.1461,0.1121,0.0437,0.727,0.0135,0.0000,39.1,Good,0
1,2,20.5,1280,136.4,1.38,0.32,38.9,12.61,18.24,55.6,...,25.8,0.1342,0.1550,0.1099,1.193,0.0148,0.0176,38.6,Good,0
2,3,34.6,993,158.1,1.78,0.25,36.6,13.39,17.18,61.1,...,28.5,0.2466,0.0976,0.0758,1.299,0.0088,0.0000,40.8,Good,0
3,4,47.7,1276,205.1,2.07,0.32,34.2,13.65,17.79,62.3,...,31.6,0.2110,0.0956,0.0731,1.067,0.0102,0.0000,39.5,Good,0
4,5,62.1,1086,186.0,1.51,0.27,45.3,14.86,18.33,59.3,...,27.3,0.1183,0.0691,0.0804,1.530,0.0133,0.0000,42.5,Good,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1996,23165.2,1049,179.0,1.73,0.26,50.8,14.96,23.19,61.2,...,24.0,0.3399,0.1306,0.1633,5.508,0.1089,0.3159,45.3,Critical,1
1996,1997,23178.3,885,174.9,1.13,0.22,28.8,13.79,22.38,63.8,...,25.0,0.1694,0.1303,0.1432,5.906,0.1154,0.3174,45.4,Critical,1
1997,1998,23192.1,1260,198.8,1.81,0.32,38.5,15.17,21.45,64.2,...,27.9,0.2115,0.0875,0.1575,6.228,0.1268,0.3387,46.2,Critical,1
1998,1999,23201.4,1245,146.0,1.43,0.31,30.0,16.78,22.31,63.8,...,26.7,0.2517,0.1829,0.0517,6.920,0.1208,0.3583,43.6,Critical,1
1999,2000,23211.3,1078,206.1,2.08,0.27,40.0,15.29,24.52,58.0,...,31.0,0.1555,0.0735,0.1619,6.621,0.1272,0.3456,44.0,Critical,1

In [42]:
df.isnull().sum()

sample_id                  0
timestamp_s                0
spindle_speed_rpm          0
feed_rate_mm_min           0
depth_of_cut_mm            0
cutting_speed_m_min        0
material_hardness_HRC      0
spindle_motor_current_A    0
spindle_torque_Nm          0
spindle_temp_C             0
coolant_temp_C             0
ambient_temp_C             0
vibration_x_g              0
vibration_y_g              0
vibration_z_g              0
surface_roughness_Ra       0
dimensional_error_mm       0
tool_wear_mm               0
cycle_time_s               0
tool_condition             0
fault_label                0
dtype: int64

In [43]:
df.columns

Index(['sample_id', 'timestamp_s', 'spindle_speed_rpm', 'feed_rate_mm_min',
       'depth_of_cut_mm', 'cutting_speed_m_min', 'material_hardness_HRC',
       'spindle_motor_current_A', 'spindle_torque_Nm', 'spindle_temp_C',
       'coolant_temp_C', 'ambient_temp_C', 'vibration_x_g', 'vibration_y_g',
       'vibration_z_g', 'surface_roughness_Ra', 'dimensional_error_mm',
       'tool_wear_mm', 'cycle_time_s', 'tool_condition', 'fault_label'],
      dtype='object')

In [44]:
df.drop(columns=['tool_condition'], inplace=True)

In [45]:
df.columns

Index(['sample_id', 'timestamp_s', 'spindle_speed_rpm', 'feed_rate_mm_min',
       'depth_of_cut_mm', 'cutting_speed_m_min', 'material_hardness_HRC',
       'spindle_motor_current_A', 'spindle_torque_Nm', 'spindle_temp_C',
       'coolant_temp_C', 'ambient_temp_C', 'vibration_x_g', 'vibration_y_g',
       'vibration_z_g', 'surface_roughness_Ra', 'dimensional_error_mm',
       'tool_wear_mm', 'cycle_time_s', 'fault_label'],
      dtype='object')

In [46]:
X= df[['sample_id', 'timestamp_s', 'spindle_speed_rpm', 'feed_rate_mm_min',
       'depth_of_cut_mm', 'cutting_speed_m_min', 'material_hardness_HRC',
       'spindle_motor_current_A', 'spindle_torque_Nm', 'spindle_temp_C',
       'coolant_temp_C', 'ambient_temp_C', 'vibration_x_g', 'vibration_y_g',
       'vibration_z_g', 'surface_roughness_Ra', 'dimensional_error_mm',
       'tool_wear_mm', 'cycle_time_s']]
y=df['fault_label']

In [47]:
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)

In [48]:
X_train.head()

,sample_id,timestamp_s,spindle_speed_rpm,feed_rate_mm_min,depth_of_cut_mm,cutting_speed_m_min,material_hardness_HRC,spindle_motor_current_A,spindle_torque_Nm,spindle_temp_C,coolant_temp_C,ambient_temp_C,vibration_x_g,vibration_y_g,vibration_z_g,surface_roughness_Ra,dimensional_error_mm,tool_wear_mm,cycle_time_s
836,837,9674.3,1301,164.0,1.90,0.33,38.4,13.94,17.63,60.4,28.8,25.7,0.1578,0.1278,0.0417,0.753,0.0175,0.1151,41.9
575,576,6652.8,1058,165.3,0.89,0.27,44.0,13.98,19.38,55.7,29.9,25.6,0.1042,0.1529,0.1191,1.743,0.0109,0.1003,42.6
557,558,6455.4,1050,180.6,1.15,0.26,42.2,13.10,16.92,57.5,26.2,30.2,0.2021,0.1173,0.1192,1.638,0.0160,0.1085,48.8
1235,1236,14305.5,1354,226.9,1.79,0.34,47.1,13.99,19.39,59.4,26.3,30.7,0.1510,0.1445,0.1074,1.915,0.0240,0.1929,46.1
1360,1361,15746.8,1178,149.3,1.60,0.30,20.0,11.27,15.26,55.9,30.6,25.5,0.1865,0.1577,0.0502,1.899,0.0241,0.2530,41.4

In [49]:
from sklearn.preprocessing import StandardScaler
scaler= StandardScaler()

In [50]:
X_train_scaled= scaler.fit_transform(X_train)
X_test_scaled= scaler.transform(X_test)

In [51]:
X_train_scaled

array([[-0.27805664, -0.28119783,  0.67295851, ..., -0.50990942,
        -0.58948025, -0.82082943],
       [-0.73316439, -0.73590212, -0.9441726 , ..., -0.67134337,
        -0.73493438, -0.61069024],
       [-0.76455113, -0.76560876, -0.99741149, ..., -0.54659895,
        -0.65434493,  1.25054265],
       ...,
       [-0.23620765, -0.24015932,  0.220428  , ..., -0.4878957 ,
        -0.2346901 , -0.82082943],
       [ 0.80827336,  0.80295927,  1.05894042, ..., -0.15035197,
         0.75400488, -1.66138622],
       [ 0.22761864,  0.22881139,  2.29008963, ..., -0.41207066,
         0.2547434 , -0.19041184]], shape=(1400, 19))

In [52]:
print(y_train.value_counts().sort_index())

fault_label
0    1086
1     203
2      56
3      55
Name: count, dtype: int64

In [53]:
from sklearn.ensemble import RandomForestClassifier
rf_model=RandomForestClassifier(n_estimators=100, class_weight='balanced', random_state=42, n_jobs=-1)

In [54]:
rf_model.fit(X_train_scaled, y_train)

RandomForestClassifier(class_weight='balanced', n_jobs=-1, random_state=42)